In [1]:
#Q.1 - Create a numpy array with 10 elements of the shape(10,1)
#using np.random and find out the mean of the elements using basic numpy functions.

import numpy as np
arr = np.random.random((10,1))
print(arr)
np.mean(arr)

[[0.39826399]
 [0.94327638]
 [0.34700033]
 [0.94143972]
 [0.37819227]
 [0.40786729]
 [0.86899344]
 [0.98280525]
 [0.85281449]
 [0.35648463]]


0.6477137783279702

In [4]:
#Q.2 - Create a numpy array with 20 elements of the shape(20,1)
#using np.random find the variance and standard deviation of the elements.

arr1 = np.random.random((20,1))
print(arr1)
print(np.var(arr1))
print(np.std(arr1))

[[0.07838224]
 [0.95683961]
 [0.77255413]
 [0.51236388]
 [0.36858708]
 [0.55117762]
 [0.89328126]
 [0.81375674]
 [0.56611318]
 [0.34519913]
 [0.18311712]
 [0.48897249]
 [0.51719299]
 [0.83309296]
 [0.14838241]
 [0.95585196]
 [0.42186994]
 [0.02257347]
 [0.27203616]
 [0.08740637]]
0.08797338562100446
0.29660307756495796


In [6]:
#Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random.
#Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25).
#Using basic numpy math functions only find the sum of all the elements of the new matrix.

A = np.random.random((10,20))
print(A)
print('*'*50)
B = np.random.random((20,25))
print(B)
print('*'*50)
C = np.matmul(A,B)
print(C)
print('*'*50)
print(np.reshape(C,(10,25)))
print(np.sum(C))

[[0.4294449  0.89069754 0.11355743 0.32992368 0.87665079 0.84980481
  0.46916817 0.73125369 0.6416159  0.81653641 0.4389576  0.43400488
  0.72975349 0.283113   0.10749396 0.90447999 0.15871683 0.62465901
  0.21045728 0.05858079]
 [0.41444597 0.87643614 0.49084882 0.60171324 0.06811033 0.58766398
  0.42101689 0.45746894 0.84044187 0.68642072 0.71140002 0.45467715
  0.12175603 0.42229739 0.42628756 0.21972178 0.5545394  0.22519123
  0.39515896 0.66906578]
 [0.73976536 0.98146763 0.11440254 0.96501088 0.99929384 0.72880479
  0.15480608 0.84220283 0.83645686 0.77587785 0.12728264 0.11431717
  0.72864463 0.68878753 0.08589855 0.70185895 0.66282523 0.7795986
  0.01442149 0.99595663]
 [0.72762226 0.13626699 0.81640574 0.82406555 0.83353091 0.48109721
  0.96870764 0.19125006 0.12496704 0.7883613  0.32159338 0.19423362
  0.98582095 0.88818417 0.66108538 0.62112554 0.34705061 0.52048011
  0.20139572 0.07830927]
 [0.54742871 0.22525221 0.85485329 0.97870827 0.30754761 0.36405346
  0.18111723 0.91

In [7]:
#Q.4 - Create a numpy array A of shape(10,1).
#Using the basic operations of the numpy array generate an array of shape(10,1) 
#such that each element is the following function applied on each element of A. 
#f(x)=1 / (1 + exp(-x)) 
#Apply this function to each element of A and print the new array holding the value the function returns
#Example:
#a=[a1,a2,a3]   
#n(new array to be printed )=[ f(a1), f(a2), f(a3)]

A1 = np.random.random((10,1))
print(A1)
def func(x):
    return (1 / (1 + np.exp(-x)))

result = np.apply_along_axis(func, 0, A1)

print('*'*40)

print(result)

[[0.46730142]
 [0.78063954]
 [0.00198588]
 [0.84885633]
 [0.04753506]
 [0.93039681]
 [0.99570709]
 [0.28963541]
 [0.88978503]
 [0.55574022]]
****************************************
[[0.61474484]
 [0.68581793]
 [0.50049647]
 [0.70032718]
 [0.51188153]
 [0.71715578]
 [0.73021371]
 [0.57190687]
 [0.70884581]
 [0.63546634]]
